# input 8 numbers from the user and display all the unique number(once)

s = set()
s1 = int(input("Enter number 1: "))
s.add(s1)
s2 = int(input("Enter number 2: "))
s.add(s2)
s3 = int(input("Enter number 3: "))
s.add(s3)
s4 = int(input("Enter number 4: "))
s.add(s4)
s5 = int(input("Enter number 5: "))
s.add(s5)
s6 = int(input("Enter number 6: "))
s.add(s6)
s7 = int(input("Enter number 7: "))
s.add(s7)
s8 = int(input("Enter number 8: "))
s.add(s8)

print(s)